const $=id=>document.getElementById(id);const fmt=n=>(Number(n)||0).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';const store=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const load=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}};
let clients=load('tk_clients_v2'),quotes=load('tk_quotes_v2'),tasks=load('tk_tasks_v2',['Compléter les informations de l’entreprise','Ajouter le premier client']);let selectedClient=null,editingClient=null,editingQuote=null;
const titles={dashboard:['Bonjour 👋','Voici un aperçu de votre activité.'],clients:['Clients','Gérez votre base clients.'],devis:['Devis','Créez et suivez vos devis.'],factures:['Factures','Facturation et règlements.'],chantiers:['Chantiers','Suivi de vos travaux.'],paiements:['Paiements','Acomptes et encaissements.'],depenses:['Dépenses','Achats et frais professionnels.'],catalogue:['Catalogue','Prestations et tarifs.'],documents:['Documents','Vos documents TECH KONFORT.'],stats:['Statistiques','Suivez votre activité.'],parametres:['Paramètres','Configurez TECH KONFORT Gestion.']};
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));$(id).classList.add('active-page');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('pageTitle').textContent=titles[id][0];$('pageSub').textContent=titles[id][1];$('sidebar').classList.remove('open');renderAll()}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('mobileMenu').onclick=()=>$('sidebar').classList.toggle('open');$('today').textContent=new Intl.DateTimeFormat('fr-FR',{weekday:'short',day:'2-digit',month:'short'}).format(new Date());
function clientId(){return 'CLI-'+String(clients.length+1).padStart(4,'0')}function quoteNum(){const y=new Date().getFullYear();let n=1;if(quotes.length){n=Math.max(...quotes.map(q=>+(q.num.split('-').pop())||0))+1}return `DEV-${y}-${String(n).padStart(4,'0')}`}
function openClient(c=null){editingClient=c?.id||null;$('clientDlgTitle').textContent=c?'Modifier le client':'Nouveau client';$('cname').value=c?.name||'';$('cphone').value=c?.phone||'';$('cmail').value=c?.mail||'';$('cbill').value=c?.bill||'';$('csite').value=c?.site||'';$('cnotes').value=c?.notes||'';$('clientDialog').showModal()}document.querySelectorAll('[data-action="newClient"]').forEach(b=>b.onclick=()=>openClient());$('closeClient').onclick=$('cancelClient').onclick=()=>$('clientDialog').close();$('clientForm').onsubmit=e=>{e.preventDefault();const c={id:editingClient||clientId(),name:$('cname').value.trim(),phone:$('cphone').value.trim(),mail:$('cmail').value.trim(),bill:$('cbill').value.trim(),site:$('csite').value.trim(),notes:$('cnotes').value.trim(),created:new Date().toISOString()};if(!c.name)return;if(editingClient){const old=clients.find(x=>x.id===editingClient);c.created=old.created;clients=clients.map(x=>x.id===editingClient?c:x)}else clients.unshift(c);store('tk_clients_v2',clients);selectedClient=c.id;$('clientDialog').close();renderAll();toast(editingClient?'Client modifié':'Client enregistré')};
function renderClients(){const q=($('clientSearch')?.value||'').toLowerCase();const arr=clients.filter(c=>[c.name,c.phone,c.mail,c.site].join(' ').toLowerCase().includes(q));$('clientCount').textContent=`${arr.length} client${arr.length>1?'s':''}`;$('clientRows').innerHTML=arr.length?arr.map(c=>`<div class="clientCard ${selectedClient===c.id?'active':''}" data-cid="${c.id}"><div class="clientTop"><b>${esc(c.name)}</b><span class="pill">${c.id}</span></div><small>${esc(c.phone||c.mail||'Aucune coordonnée')}</small><small>${esc(c.site||'Adresse chantier non renseignée')}</small></div>`).join(''):`<div class="empty"><div>♙</div><b>Aucun client</b><p>Ajoutez votre premier client.</p></div>`;document.querySelectorAll('[data-cid]').forEach(x=>x.onclick=()=>{selectedClient=x.dataset.cid;renderClients();renderClientDetail()});renderClientDetail();$('qclient').innerHTML='<option value="">Choisir un client</option>'+clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}
function renderClientDetail(){const c=clients.find(x=>x.id===selectedClient);if(!c){$('clientDetail').innerHTML='<div class="empty"><div>♙</div><b>Sélectionnez un client</b><p>Sa fiche complète apparaîtra ici.</p></div>';return}const cq=quotes.filter(q=>q.clientId===c.id);$('clientDetail').innerHTML=`<div class="detailHead"><div><span class="pill">${c.id}</span><h2>${esc(c.name)}</h2><p>${esc(c.site||'Adresse chantier non renseignée')}</p></div><div><button class="secondary" id="editClient">Modifier</button> <button class="primary" id="clientQuote">＋ Devis</button></div></div><div class="detailGrid"><div class="infoBox"><small>Téléphone</small>${esc(c.phone||'—')}</div><div class="infoBox"><small>E-mail</small>${esc(c.mail||'—')}</div><div class="infoBox"><small>Facturation</small>${esc(c.bill||'—')}</div><div class="infoBox"><small>Chantier</small>${esc(c.site||'—')}</div></div><div class="tabs"><button class="active">Historique</button><button>Notes</button><button>Documents</button><button>Photos</button></div><div class="history">${cq.length?cq.map(q=>`<div class="historyRow"><b>${q.num} · ${esc(q.object||'Sans objet')}</b><span>${new Date(q.date).toLocaleDateString('fr-FR')}</span><strong>${fmt(q.total)}</strong></div>`).join(''):'<div class="empty"><b>Aucun devis pour ce client</b><p>Créez le premier directement depuis sa fiche.</p></div>'}<div class="infoBox"><small>Notes client</small>${esc(c.notes||'Aucune note')}</div></div>`;$('editClient').onclick=()=>openClient(c);$('clientQuote').onclick=()=>{newQuote(c.id);go('devis')}}
$('clientSearch').oninput=renderClients;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function addQuoteLine(desc='',qty=1,price=0){const d=document.createElement('div');d.className='line';d.innerHTML=`<input class="desc" placeholder="Prestation ou fourniture" value="${esc(desc)}"><input class="qty" type="number" min="0" step="0.01" value="${qty}"><input class="price" type="number" min="0" step="0.01" value="${price}"><b class="ltotal">0,00 €</b><button class="delLine" type="button">×</button>`;$('qLines').appendChild(d);d.querySelectorAll('input').forEach(i=>i.oninput=calc);d.querySelector('.delLine').onclick=()=>{d.remove();calc()};calc()}
function calc(){let total=0;document.querySelectorAll('#qLines .line').forEach(l=>{const t=(+l.querySelector('.qty').value||0)*(+l.querySelector('.price').value||0);l.querySelector('.ltotal').textContent=fmt(t);total+=t});$('qtotal').textContent=fmt(total);$('qdeposit').textContent=fmt(total*.3);$('qremain').textContent=fmt(total*.7);return total}
function newQuote(client=''){editingQuote=null;$('qnum').value=quoteNum();$('qobject').value='';$('qdate').value=new Date().toISOString().slice(0,10);let v=new Date();v.setDate(v.getDate()+30);$('qvalid').value=v.toISOString().slice(0,10);$('qclient').value=client;$('qnotes').value='';$('qLines').innerHTML='';addQuoteLine('Diagnostic / intervention',1,65);addQuoteLine('',1,0)}document.querySelectorAll('[data-action="newQuote"]').forEach(b=>b.onclick=()=>{go('devis');newQuote()});$('addLine').onclick=()=>addQuoteLine();$('clearQuote').onclick=()=>newQuote();
$('saveQuote').onclick=()=>{if(!$('qclient').value){toast('Choisissez un client');return}const lines=[...document.querySelectorAll('#qLines .line')].map(l=>({desc:l.querySelector('.desc').value,qty:+l.querySelector('.qty').value||0,price:+l.querySelector('.price').value||0})).filter(x=>x.desc.trim());const q={id:editingQuote||crypto.randomUUID?.()||String(Date.now()),num:$('qnum').value,clientId:$('qclient').value,object:$('qobject').value.trim(),date:$('qdate').value,valid:$('qvalid').value,notes:$('qnotes').value,lines,total:calc(),status:'En attente'};if(editingQuote)quotes=quotes.map(x=>x.id===editingQuote?q:x);else quotes.unshift(q);store('tk_quotes_v2',quotes);editingQuote=q.id;renderAll();toast('Devis enregistré')};
function editQuote(id){const q=quotes.find(x=>x.id===id);if(!q)return;editingQuote=id;$('qnum').value=q.num;$('qclient').value=q.clientId;$('qobject').value=q.object;$('qdate').value=q.date;$('qvalid').value=q.valid;$('qnotes').value=q.notes||'';$('qLines').innerHTML='';q.lines.forEach(x=>addQuoteLine(x.desc,x.qty,x.price));calc()}
function renderQuotes(){const s=($('quoteSearch')?.value||'').toLowerCase();const arr=quotes.filter(q=>{const c=clients.find(x=>x.id===q.clientId);return [q.num,q.object,c?.name].join(' ').toLowerCase().includes(s)});$('quoteRows').innerHTML=arr.length?arr.map(q=>{const c=clients.find(x=>x.id===q.clientId);return `<div class="quoteCard" data-qid="${q.id}"><b>${q.num} · ${fmt(q.total)}</b><small>${esc(c?.name||'Client supprimé')}</small><small>${esc(q.object||'Sans objet')} · ${q.status}</small></div>`}).join(''):'<div class="empty"><b>Aucun devis</b><p>Créez votre premier devis.</p></div>';document.querySelectorAll('[data-qid]').forEach(x=>x.onclick=()=>editQuote(x.dataset.qid))}
$('quoteSearch').oninput=renderQuotes;
function renderDashboard(){$('kClients').textContent=clients.length;$('kQuotes').textContent=quotes.length;$('kQuoteAmount').textContent=fmt(quotes.reduce((a,q)=>a+q.total,0));$('dashQuotes').innerHTML=quotes.length?quotes.slice(0,4).map(q=>{const c=clients.find(x=>x.id===q.clientId);return `<div class="historyRow"><b>${q.num}<small style="display:block;color:#98a0a6">${esc(c?.name||'')}</small></b><span>${esc(q.object||'')}</span><strong>${fmt(q.total)}</strong></div>`}).join(''):'<div>▤</div><b>Aucun devis pour le moment</b><p>Votre premier devis apparaîtra ici.</p>'}
function renderTasks(){$('taskList').innerHTML=tasks.map((t,i)=>`<label><input type="checkbox" data-task="${i}"> ${esc(t)}</label>`).join('')}$('addTask').onclick=()=>{const t=prompt('Nouvelle tâche');if(t){tasks.push(t);store('tk_tasks_v2',tasks);renderTasks()}};$('taskList').onclick=e=>{if(e.target.dataset.task!==undefined){tasks.splice(+e.target.dataset.task,1);store('tk_tasks_v2',tasks);setTimeout(renderTasks,200)}};
$('saveSettings').onclick=()=>toast('Paramètres enregistrés sur cet appareil');$('globalSearch').onkeydown=e=>{if(e.key==='Enter'){const q=e.target.value.toLowerCase();const c=clients.find(x=>x.name.toLowerCase().includes(q));if(c){selectedClient=c.id;go('clients')}else toast('Aucun résultat')}};
function renderAll(){renderClients();renderQuotes();renderDashboard();renderTasks()}renderAll();newQuote();

// ===== TECH KONFORT V2 modules =====
let invoices=load('tk_invoices_v2'),payments=load('tk_payments_v2'),projects=load('tk_projects_v2'),expenses=load('tk_expenses_v2');
let catalog=load('tk_catalog_v2',[{id:'CAT-001',name:'Diagnostic / intervention',cat:'Dépannage',price:65},{id:'CAT-002',name:'Intervention minimum',cat:'Dépannage',price:75},{id:'CAT-003',name:'Remplacement robinet',cat:'Sanitaire',price:95},{id:'CAT-004',name:'Remplacement WC au sol',cat:'Sanitaire',price:185},{id:'CAT-005',name:'Groupe de sécurité chauffe-eau',cat:'Chauffage',price:110},{id:'CAT-006',name:'Déplacement 0–10 km',cat:'Déplacement',price:20}]);
const uid=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());
const invNum=()=>`FAC-${new Date().getFullYear()}-${String(invoices.length?Math.max(...invoices.map(x=>+(x.num.split('-').pop())||0))+1:1).padStart(4,'0')}`;
function clientName(id){return clients.find(c=>c.id===id)?.name||'Client supprimé'}
function paidFor(invId){return payments.filter(p=>p.invoiceId===invId).reduce((a,p)=>a+p.amount,0)}
function createInvoiceFromQuote(q){if(!q)return;let existing=invoices.find(i=>i.quoteId===q.id);if(existing){toast('Facture déjà créée');go('factures');return}const inv={id:uid(),num:invNum(),quoteId:q.id,clientId:q.clientId,object:q.object,date:new Date().toISOString().slice(0,10),lines:q.lines,total:q.total,status:'À payer'};invoices.unshift(inv);store('tk_invoices_v2',invoices);q.status='Accepté / facturé';store('tk_quotes_v2',quotes);if(!projects.find(p=>p.quoteId===q.id)){projects.unshift({id:uid(),clientId:q.clientId,quoteId:q.id,name:q.object||'Chantier',status:'À planifier',progress:10,notes:''});store('tk_projects_v2',projects)}renderAll();go('factures');toast('Facture créée depuis le devis')}
function renderInvoices(){if(!$('invoiceRows'))return;let total=invoices.reduce((a,i)=>a+i.total,0),paid=payments.reduce((a,p)=>a+p.amount,0);$('invTotal').textContent=fmt(total);$('invPaid').textContent=fmt(paid);$('invDue').textContent=fmt(Math.max(0,total-paid));$('invoiceRows').innerHTML=invoices.length?invoices.map(i=>{let p=paidFor(i.id),due=Math.max(0,i.total-p),st=due<.01?'Payée':p>0?'Partielle':'À payer';return `<tr><td><b>${i.num}</b></td><td>${esc(clientName(i.clientId))}</td><td>${esc(i.object||'—')}</td><td>${fmt(i.total)}</td><td>${fmt(p)}</td><td><span class="status">${st}</span></td><td class="actions"><button class="secondary mini" onclick="printDoc('invoice','${i.id}')">PDF / Imprimer</button><button class="primary mini" onclick="quickPay('${i.id}')">＋ Paiement</button></td></tr>`}).join(''):'<tr><td colspan="7"><div class="emptyModule">Aucune facture. Transformez un devis accepté en facture.</div></td></tr>'}
function quickPay(invId){const i=invoices.find(x=>x.id===invId);if(!i)return;const due=Math.max(0,i.total-paidFor(i.id));if(!due){toast('Cette facture est déjà soldée');return}let val=prompt(`Montant reçu pour ${i.num} (reste ${fmt(due)})`,String(due.toFixed(2)).replace('.',','));if(val===null)return;let amount=Number(val.replace(',','.'));if(!amount||amount<0)return;let type=amount>=due-.01?'Solde':paidFor(i.id)?'Paiement':'Acompte';let mode=prompt('Mode : Virement, CB ou Espèces','Virement')||'Virement';payments.unshift({id:uid(),invoiceId:i.id,clientId:i.clientId,date:new Date().toISOString().slice(0,10),type,mode,amount});store('tk_payments_v2',payments);renderAll();toast('Paiement enregistré')}
function renderPayments(){if(!$('paymentRows'))return;let total=payments.reduce((a,p)=>a+p.amount,0),due=Math.max(0,invoices.reduce((a,i)=>a+i.total,0)-total);$('payTotal').textContent=fmt(total);$('payCount').textContent=payments.length;$('payDue').textContent=fmt(due);$('paymentRows').innerHTML=payments.length?payments.map(p=>{let i=invoices.find(x=>x.id===p.invoiceId);return `<tr><td>${new Date(p.date).toLocaleDateString('fr-FR')}</td><td>${i?.num||'—'}</td><td>${esc(clientName(p.clientId))}</td><td>${esc(p.type)}</td><td>${esc(p.mode)}</td><td><b>${fmt(p.amount)}</b></td></tr>`}).join(''):'<tr><td colspan="6"><div class="emptyModule">Aucun paiement enregistré.</div></td></tr>'}
function renderProjects(){if(!$('projectCards'))return;$('projectCards').innerHTML=projects.length?projects.map(p=>`<article class="panel"><div class="detailHead"><div><span class="status">${esc(p.status)}</span><h3>${esc(p.name)}</h3><p>${esc(clientName(p.clientId))}</p></div><div class="actions"><button class="secondary mini" onclick="advanceProject('${p.id}')">Avancer</button></div></div><div style="height:8px;background:#24292c;border-radius:8px;overflow:hidden"><i style="display:block;width:${p.progress}%;height:100%;background:#b9904c"></i></div><p>${p.progress}% · ${esc(p.notes||'Aucune note chantier')}</p></article>`).join(''):'<div class="panel emptyModule">Aucun chantier. Un chantier est créé automatiquement lors de la facturation d’un devis.</div>'}
function advanceProject(id){let p=projects.find(x=>x.id===id);if(!p)return;let stages=[['À planifier',10],['Planifié',30],['En cours',60],['Finitions',85],['Terminé',100]];let n=Math.min(stages.length-1,stages.findIndex(s=>s[0]===p.status)+1);p.status=stages[n][0];p.progress=stages[n][1];store('tk_projects_v2',projects);renderAll();toast('Chantier mis à jour')}
function renderExpenses(){if(!$('expenseRows'))return;let total=expenses.reduce((a,e)=>a+e.amount,0),ym=new Date().toISOString().slice(0,7),month=expenses.filter(e=>e.date.startsWith(ym)).reduce((a,e)=>a+e.amount,0);$('expenseTotal').textContent=fmt(total);$('expenseMonth').textContent=fmt(month);$('expenseCount').textContent=expenses.length;$('expenseRows').innerHTML=expenses.length?expenses.map(e=>`<tr><td>${new Date(e.date).toLocaleDateString('fr-FR')}</td><td>${esc(e.vendor)}</td><td>${esc(e.cat)}</td><td>${esc(e.label)}</td><td><b>${fmt(e.amount)}</b></td></tr>`).join(''):'<tr><td colspan="5"><div class="emptyModule">Aucune dépense enregistrée.</div></td></tr>'}
function addExpense(){let vendor=prompt('Fournisseur');if(!vendor)return;let label=prompt('Libellé','Fournitures chantier')||'Dépense';let cat=prompt('Catégorie','Fournitures')||'Autre';let v=prompt('Montant TTC','0');if(v===null)return;let amount=Number(v.replace(',','.'));if(!amount)return;expenses.unshift({id:uid(),date:new Date().toISOString().slice(0,10),vendor,label,cat,amount});store('tk_expenses_v2',expenses);renderAll();toast('Dépense ajoutée')}
function renderCatalog(){if(!$('catalogRows'))return;$('catalogRows').innerHTML=catalog.map(c=>`<tr><td>${c.id}</td><td>${esc(c.name)}</td><td>${esc(c.cat)}</td><td><b>${fmt(c.price)}</b></td><td><button class="secondary mini" onclick="useCatalog('${c.id}')">Ajouter au devis</button></td></tr>`).join('')}
function useCatalog(id){let c=catalog.find(x=>x.id===id);if(!c)return;go('devis');addQuoteLine(c.name,1,c.price);toast('Ajouté au devis')}
function addCatalog(){let name=prompt('Nom de la prestation');if(!name)return;let cat=prompt('Catégorie','Sanitaire')||'Autre';let v=prompt('Prix indicatif','0');if(v===null)return;catalog.push({id:'CAT-'+String(catalog.length+1).padStart(3,'0'),name,cat,price:Number(v.replace(',','.'))||0});store('tk_catalog_v2',catalog);renderAll()}
function renderDocuments(){if(!$('documentRows'))return;$('docQuotes').textContent=quotes.length;$('docInvoices').textContent=invoices.length;$('docClients').textContent=clients.length;let docs=[...quotes.map(q=>({type:'quote',id:q.id,num:q.num,name:q.object,client:q.clientId,total:q.total})),...invoices.map(i=>({type:'invoice',id:i.id,num:i.num,name:i.object,client:i.clientId,total:i.total}))];$('documentRows').innerHTML=docs.length?docs.map(d=>`<div class="historyRow"><b>${d.num}<small style="display:block;color:#98a0a6">${esc(clientName(d.client))}</small></b><span>${esc(d.name||'Document')}</span><strong>${fmt(d.total)} <button class="secondary mini" onclick="printDoc('${d.type}','${d.id}')">PDF / Imprimer</button></strong></div>`).join(''):'<div class="emptyModule">Les devis et factures apparaîtront ici.</div>'}
function printDoc(type,id){let d=type==='quote'?quotes.find(x=>x.id===id):invoices.find(x=>x.id===id);if(!d)return;let c=clients.find(x=>x.id===d.clientId);let title=type==='quote'?'DEVIS':'FACTURE';let lines=d.lines.map(x=>`<tr><td>${esc(x.desc)}</td><td>${x.qty}</td><td>${fmt(x.price)}</td><td>${fmt(x.qty*x.price)}</td></tr>`).join('');let extra=type==='quote'?`<p><b>Acompte conseillé (30 %) :</b> ${fmt(d.total*.3)}</p>`:`<p><b>Déjà réglé :</b> ${fmt(paidFor(d.id))} · <b>Reste :</b> ${fmt(Math.max(0,d.total-paidFor(d.id)))}</p>`;$('printArea').innerHTML=`<div class="docPreview"><h2>TECH KONFORT</h2><p>Solutions techniques & amélioration de l'habitat<br>Votre projet, notre savoir-faire</p><hr><h1>${title} ${d.num}</h1><p><b>Client :</b> ${esc(c?.name||'')}<br>${esc(c?.bill||c?.site||'')}</p><p><b>Objet :</b> ${esc(d.object||'')}</p><table><thead><tr><th>Désignation</th><th>Qté</th><th>PU</th><th>Total</th></tr></thead><tbody>${lines}</tbody></table><h2 style="text-align:right">TOTAL : ${fmt(d.total)}</h2>${extra}<p style="margin-top:50px">TECH KONFORT · Document généré par TECH KONFORT Gestion</p></div>`;$('printArea').style.display='block';setTimeout(()=>{window.print();$('printArea').style.display='none'},100)}
function renderStats(){if(!$('statCA'))return;let ca=invoices.reduce((a,i)=>a+i.total,0),cash=payments.reduce((a,p)=>a+p.amount,0),exp=expenses.reduce((a,e)=>a+e.amount,0);$('statCA').textContent=fmt(ca);$('statCash').textContent=fmt(cash);$('statExpenses').textContent=fmt(exp);$('statMargin').textContent=fmt(cash-exp);$('statQuotes').textContent=quotes.length;$('statClients').textContent=clients.length;$('statsBars').innerHTML=[ca,cash,exp].map((v,i)=>`<i title="${fmt(v)}" style="height:${Math.max(8,Math.min(100,v/(Math.max(ca,cash,exp,1))*100))}%"></i>`).join('')}
function updateDashV2(){let ca=invoices.reduce((a,i)=>a+i.total,0),cash=payments.reduce((a,p)=>a+p.amount,0);let cards=document.querySelectorAll('.kpis article strong');if(cards[3])cards[3].textContent=fmt(Math.max(0,ca-cash))}
$('newInvoice').onclick=()=>{if(!quotes.length){toast('Créez d’abord un devis');return}let opts=quotes.map((q,i)=>`${i+1}. ${q.num} - ${clientName(q.clientId)} - ${fmt(q.total)}`).join('\n');let n=prompt('Quel devis facturer ?\n'+opts,'1');if(n)createInvoiceFromQuote(quotes[+n-1])};
$('newPayment').onclick=()=>{if(!invoices.length){toast('Aucune facture à régler');return}let opts=invoices.map((i,n)=>`${n+1}. ${i.num} - reste ${fmt(Math.max(0,i.total-paidFor(i.id)))}`).join('\n');let n=prompt('Choisissez une facture :\n'+opts,'1');if(n)quickPay(invoices[+n-1]?.id)};
$('newProject').onclick=()=>{if(!clients.length){toast('Ajoutez un client');return}let name=prompt('Nom du chantier','Rénovation salle de bain');if(!name)return;projects.unshift({id:uid(),clientId:clients[0].id,quoteId:null,name,status:'À planifier',progress:10,notes:''});store('tk_projects_v2',projects);renderAll()};
$('newExpense').onclick=addExpense;$('newCatalog').onclick=addCatalog;
$('exportData').onclick=()=>{let data={version:2,date:new Date().toISOString(),clients,quotes,invoices,payments,projects,expenses,catalog,tasks};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='TECH_KONFORT_sauvegarde_'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href);toast('Sauvegarde exportée')};
$('importData').onclick=()=>$('importFile').click();$('importFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);[['clients','tk_clients_v2'],['quotes','tk_quotes_v2'],['invoices','tk_invoices_v2'],['payments','tk_payments_v2'],['projects','tk_projects_v2'],['expenses','tk_expenses_v2'],['catalog','tk_catalog_v2'],['tasks','tk_tasks_v2']].forEach(([k,key])=>{if(d[k])store(key,d[k])});location.reload()}catch{toast('Fichier invalide')}};r.readAsText(f)};
// add quote -> invoice action on quote cards by double click
const oldRQ=renderQuotes;renderQuotes=function(){oldRQ();document.querySelectorAll('[data-qid]').forEach(x=>{x.ondblclick=()=>createInvoiceFromQuote(quotes.find(q=>q.id===x.dataset.qid))})};
const oldRA=renderAll;renderAll=function(){oldRA();renderInvoices();renderPayments();renderProjects();renderExpenses();renderCatalog();renderDocuments();renderStats();updateDashV2()};renderAll();
